#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config focused_border_color \#FFFFFF
bspc config normal_border_color \#D2D8E0
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true
bspc config automatic_scheme	spiral

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc rule -a kitty state=tiled
bspc rule -a tilix state=tiled
bspc rule -a firefox desktop='^2' state=tiled
bspc rule -a Discord state=tiled
bspc rule -a code state=tiled

# Autostart
$HOME/.screenlayout/screen.sh &
picom &
compton --restore &
polybar &
feh --bg-fill /home/aphroth/Pictures/Wallpapers/as.jpg &
xrandr -s 1360x768 &
